controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    pelvis_controller:
      type: joint_trajectory_controller/JointTrajectoryController

head_controller:
  ros__parameters:
    joints:
      - HeadYaw
      - HeadPitch
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

pelvis_controller:
  ros__parameters:
    joints:
      - HipRoll
      - HipPitch
      - KneePitch
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
