<?xml version="1.0"?>
<package format="2">
  <name>pepper_gazebo_plugin</name>
  <version>0.0.4</version>
  <description>Gazebo plugin for Pepper robot</description>

  <maintainer email="natalia.lyubova@gmail.com">Natalia Lyubova</maintainer>
  <author email="natalia.lyubova@gmail.com">Natalia Lyubova</author>
  <author email="mikael.arguedas@gmail.com">Mikael Arguedas</author>

  <license>Apache 2.0</license>

  <url type="bugtracker">https://github.com/ros-naoqi/pepper_virtual/issues</url>
  <url type="repository">https://github.com/ros-naoqi/pepper_virtual.git</url>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>gazebo_ros</build_depend>
  <build_depend>pepper_description</build_depend>

  <exec_depend>gazebo_plugins</exec_depend>
  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>gazebo_ros_control</exec_depend>
  <exec_depend>pepper_control</exec_depend>
  <exec_depend>pepper_description</exec_depend>
  <exec_depend>ros_control</exec_depend>
  <exec_depend>ros_controllers</exec_depend>
</package>
